### For reference, see `open5gs.conf`

db_uri: mongodb://192.168.26.5/open5gs

logger:
    file: /var/log/open5gs/hss.log
    trace: 
        app: 1
        diameter: 1

parameter:

hss:
    freeDiameter: /etc/open5gs/freeDiameter/hss.conf
